### ISSUE TITLE
[feature request] add option for 4:3 in 480p

### ISSUE THREAD

**Issue by cutrus** [Lynx64/WiiVCLaunch#1]
I think it would be a good idea to add an option for running wii games in 4:3 when the resolution is set to 480p.

**Comment by Andrew1Hawes** [comment]
I have considered adding more (niche) resolution options as part of a future update. This is a good example of one. I've added this to my todo list. It will be a long time coming.

**Comment by Wolfy76700** [comment]
I’ll upvote this one since it would be convenient to just have that saved instead of having to use the Settings Editor GUI homebrew every time (Which I can’t do if  use Wii U VC but I’m fine with using the main vWii menu for now)
