### ISSUE TITLE
Wii U gets softlocked at the launch for the vWii when enabling "Permanent Wii Internet Settings"

### ISSUE THREAD

**Issue by Bluestk** [Lynx64/WiiVCLaunch#8]
For some reason, if I pick the "Permanent Wii Internet Settings" option, whenever I launch the Wii Menu or any Wii VC title, it gets softlocked at the boot screen with me unable to to do anything but turn off the console manually, I tested combinations and it's only cause by the "Permanent Wii Internet Settings" when set to on, any ideas on why that might happen?

**Comment by Andrew1Hawes** [comment]
I will get round to this 👍.

**Comment by Andrew1Hawes** [comment]
Should be fixed in version 1.1. Let me know if it's not.

**Comment by Bluestk** [comment]
I tested it and it doesn't have the issue anymore, but it doesn't seem to do anything from my testing, it just ends with Wiiconnect24 off every time I launch, regardless of having the "Permanent Wii Internet Settings" and/or the Preserve SYSCONF on Wii VC title launch on, is there something I'm missing? I do have Priiloader btw.
